### PR TITLE
Added voxel-life demo link and thumbnail

### PR DESCRIPTION
**Pull request by theoxylo**
hey, I have a working demo of my voxel-life game, so I went ahead and added it... hope you like it!

Besides the game of life stuff, the demo also has crude multi-voxel copy/paste functionality. I want to figure out a good format for exchanging voxel data, for example one that could also be used with voxel-painter. I guess I need to research to find out what has already been done in that area...

### CODE REVIEW

**Comment by max-mapper** [comment]
@theoxylo nice! i'll check it out. coincidentally I was just hacking on voxel-select, which is based on voxel-highlight http://maxogden.github.com/voxel-select/

press shift to start a selection and shift+click a point to end it

**Comment by max-mapper** [comment]
@theoxylo in terms of the format for exchanging voxel data this is what we have so far:

https://github.com/maxogden/voxel-engine/blob/master/README.md#voxel-interchange-format

(open to suggestions on that)

**Comment by theoxylo** [comment]
@maxogden hey, that is pretty much what I am doing now, where the dimensions are required to interpret the packed array, and the array contains an entry for every voxel, even those that are "off".

but I was looking at your voxel-painter where you record the position of each voxel as well. it seems like this might be more useful in the long run:
- only need an array element for voxels that are "on"
- can deal with each voxel independently, e.g. with an array map function callback
- it might be easier to do transforms. for example, if I want to rotate the selection about the y-axis by a quarter turn, I can transform each voxel's position (as opposed to rearranging the packed array order)

I suppose we could have multiple formats with utilities to convert between them as needed...

**Comment by max-mapper** [comment]
ahh yea that makes sense, just an array of [x,y,z,value] vectors

**Comment by theoxylo** [comment]
Whichever you prefer!

It turns out it is not hard to convert from one to the other.

Here is the easy to understand but inefficient version:

```
  function xyzToPackedIndex(x_arg, y_arg, z_arg, dims) {
    var index = 0
    for (var z = 0; z < dims[2]; z++) {
      for (var y = 0; y < dims[1]; y++) {
        for (var x = 0; x < dims[0]; x++) {
          if (x_arg === x && y_arg === y && z_arg === z) return index
          index++
        }
      }
    }
  }
```

And here is a more efficient form that gives the same answer (I think it is working now):

```
  function getPackedIndex(x_arg, y_arg, z_arg, dims) {
    return z_arg * (dims[1] * dims[0]) + y_arg * dims[0] + x_arg
  }
```

Converting in the opposite direction shouldn't be hard either, but I haven't worked on it yet:

```
  function getCoordsFromPackedIndex(index, dims) { ... }
```

I will update my voxel-life demo once I have something working!

**Comment by max-mapper** [comment]
nice, I think this kind of logic should live in voxel-chunks and we should
just use that everywhere

**Comment by theoxylo** [comment]
that would be nice!

I can contribute it but it will take me a week as I am going to be out of town.

**Pull request merged**
